import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Waves from "@/components/Waves";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-dvh">
          {/* Background Waves */}
          <div className="pointer-events-none fixed inset-0 -z-10 text-black/10 dark:text-white">
            <Waves
              lineColor="currentColor"
              backgroundColor="transparent"
              className=""
            />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
